### ISSUE TITLE
Building from source has wrong method name for QFont

### ISSUE THREAD

**Issue by RyanNerd** [tsujan/FeatherNotes#217] opened 2021-10-03 07:16 UTC
Output from `make` (Building on Linux Mint 20.2 -- Debian based)

```
/home/ryan/Downloads/feathernote/FeatherNotes-0.9.0/feathernotes/fn.cpp: In member function ‘void FeatherNotes::FN::textFontDialog()’:
/home/ryan/Downloads/feathernote/FeatherNotes-0.9.0/feathernotes/fn.cpp:2907:22: error: ‘class QFont’ has no member named ‘setFamilies’; did you mean ‘setFamily’?
 2907 |         defaultFont_.setFamilies (newFont.families()); // to override the existing font families
      |                      ^~~~~~~~~~~
      |                      setFamily
/home/ryan/Downloads/feathernote/FeatherNotes-0.9.0/feathernotes/fn.cpp:2907:43: error: ‘class QFont’ has no member named ‘families’; did you mean ‘family’?
 2907 |         defaultFont_.setFamilies (newFont.families()); // to override the existing font families
```
I manually edited line 2907 to use "familly" instead of "families":

`        defaultFont_.setFamily (newFont.family()); // to override the existing font families`

This solved the issue.
I've not used c++ in years, or I'd create a PR for this.

Also the INSTALL instructions need to include some additional dependencies:

```
sudo apt install qtbase5-dev
sudo apt install qttools5-dev
sudo apt install libqt5x11extras5-dev
```

**Comment by tsujan** [comment] 2021-10-03 07:48
Duplicate of https://github.com/tsujan/FeatherNotes/issues/181


You have an old version of Qt. Compilation against old versions is made possible in https://github.com/tsujan/FeatherNotes/commit/8f25e16dfcad9c8746df71968b97f72b006093bc

**Closed by tsujan** 2021-10-03 07:48 UTC

**Comment by tsujan** [comment] 2021-10-03 07:58
> Also the INSTALL instructions need to include some additional dependencies:

All of them were included — years ago, I used Debian Testing; so I'd put it first.
